# Problem Statement
### I am working in an MNC in London, United Kingdom for 5 years. Now my company wants to expand its business in London. So in order to do so, it has to open a lot of new shops particulary in East Central, London.
### So me being the country head of United Kingdom, the company wants me to move to the East Central London in order to look after the new shops in a more better way and also I can address any problem happening there in the new shops.
### Now the problem is that I am current living in West London with my family and in order to move to East Central London . I need to shift my family too and in order to get reimbursement from my company I need to show them a perfect location in the East Central London for my living.
### So that I can get a place which is near from every good and exotic locations of our stores in East Central London and can have my family there and also look upto these stores whenever needed.
### I am required to present a report in order to give a best location for purchasing a house in the area of East Central London.
### Since London is a very big city and according my budget the only locality I will be able to purchase a house will be in East Central. So I wanted a perfect location in that locality in which I can purchase my house and shift my family there,
### London being such a big and world famous city, it is really hard to pick up a house to live that too in the East Central London as the place is a home for many foreigners.
### I will have to show the company a detailed report of my surroundings and for that I will perform some analysis over the area of the East Central London.
# Data Description
### I will be using https://en.wikipedia.org/wiki/EC_postcode_area for the postal codes and Forthsquare for retrieving the nearby locations for comparing and obviously the Geospatial data for mapping. Also I will be using https://www.doogal.co.uk/UKPostcodesCSV.ashx?area=London for the latitudes and longitudes.These will help me to find the cluster of areas and help me to find a best and suitable location for my new house in East Central London. I will present my report on the basis of these data. Also I will be keeping in mind the location every places around the East Central London for preparing my report.

In [2]:
import pandas as pd
import numpy as np
import requests

In [3]:
url = "https://en.wikipedia.org/wiki/EC_postcode_area"

In [4]:
df=pd.read_html(url)
df=df[-4]
df

,Postcode district,Post town,Coverage,Local authority area
0,EC1A,LONDON,St Bartholomew's Hospital,"City of London, Islington"
1,EC1M,LONDON,"Clerkenwell, Farringdon","Islington, Camden, City of London"
2,EC1N,LONDON,Hatton Garden,"Camden, City of London"
3,EC1P,LONDON,NaN,non-geographic
4,EC1R,LONDON,"Finsbury, Finsbury Estate (west)","Islington, Camden"
5,EC1V,LONDON,"Finsbury (east), Moorfields Eye Hospital","Islington, Hackney"
6,EC1Y,LONDON,"St Luke's, Bunhill Fields","Islington, City of London"
7,EC2A,LONDON,Shoreditch,"Islington, Hackney, City of London"
8,EC2M,LONDON,"Broadgate, Liverpool Street",Tower Hamlets
9,EC2N,LONDON,"Old Broad Street, Tower 42",City of London
10,EC2P,LONDON,NaN,non-geographic
11,EC2R,LONDON,Bank of England,City of London
12,EC2V,LONDON,Guildhall,City of London
13,EC2Y,LONDON,Barbican,City of London
14,EC3A,LONDON,"St Mary Axe, Aldgate",City of London
15,EC3M,LONDON,"Lloyd's of London, Fenchurch Street",City of London
16,EC3N,LONDON,"Tower Hill, Tower of London","Tower Hamlets, City of London"
17,EC3P,LONDON,NaN,non-geographic
18,EC3R,LONDON,"Monument, Billingsgate",City of London
19,EC3V,LONDON,"Cornhill, Gracechurch Street, Lombard Street",City of London
20,EC4A,LONDON,Fetter Lane,"City of London, Westminster"
21,EC4M,LONDON,St Paul's,City of London
22,EC4N,LONDON,Mansion House,City of London
23,EC4P,LONDON,NaN,non-geographic
24,EC4R,LONDON,Cannon Street,City of London
25,EC4V,LONDON,Blackfriars,City of London
26,EC4Y,LONDON,Temple,"City of London, Westminster"
27,EC50,LONDON,NaN,non-geographic

In [39]:

df2=pd.read_html(url)
df2=df2[-4]
df2

,Postcode district,Post town,Coverage,Local authority area
0,EC1A,LONDON,St Bartholomew's Hospital,"City of London, Islington"
1,EC1M,LONDON,"Clerkenwell, Farringdon","Islington, Camden, City of London"
2,EC1N,LONDON,Hatton Garden,"Camden, City of London"
3,EC1P,LONDON,NaN,non-geographic
4,EC1R,LONDON,"Finsbury, Finsbury Estate (west)","Islington, Camden"
5,EC1V,LONDON,"Finsbury (east), Moorfields Eye Hospital","Islington, Hackney"
6,EC1Y,LONDON,"St Luke's, Bunhill Fields","Islington, City of London"
7,EC2A,LONDON,Shoreditch,"Islington, Hackney, City of London"
8,EC2M,LONDON,"Broadgate, Liverpool Street",Tower Hamlets
9,EC2N,LONDON,"Old Broad Street, Tower 42",City of London
10,EC2P,LONDON,NaN,non-geographic
11,EC2R,LONDON,Bank of England,City of London
12,EC2V,LONDON,Guildhall,City of London
13,EC2Y,LONDON,Barbican,City of London
14,EC3A,LONDON,"St Mary Axe, Aldgate",City of London
15,EC3M,LONDON,"Lloyd's of London, Fenchurch Street",City of London
16,EC3N,LONDON,"Tower Hill, Tower of London","Tower Hamlets, City of London"
17,EC3P,LONDON,NaN,non-geographic
18,EC3R,LONDON,"Monument, Billingsgate",City of London
19,EC3V,LONDON,"Cornhill, Gracechurch Street, Lombard Street",City of London
20,EC4A,LONDON,Fetter Lane,"City of London, Westminster"
21,EC4M,LONDON,St Paul's,City of London
22,EC4N,LONDON,Mansion House,City of London
23,EC4P,LONDON,NaN,non-geographic
24,EC4R,LONDON,Cannon Street,City of London
25,EC4V,LONDON,Blackfriars,City of London
26,EC4Y,LONDON,Temple,"City of London, Westminster"
27,EC50,LONDON,NaN,non-geographic

In [7]:
df.drop(columns=["Local authority area"],axis=1,inplace=True)

In [8]:
df.rename(columns={"Coverage":"Neighbourhood"})

   Postcode district                                 Neighbourhood
0               EC1A                     St Bartholomew's Hospital
1               EC1M                       Clerkenwell, Farringdon
2               EC1N                                 Hatton Garden
3               EC1P                                           NaN
4               EC1R              Finsbury, Finsbury Estate (west)
5               EC1V      Finsbury (east), Moorfields Eye Hospital
6               EC1Y                     St Luke's, Bunhill Fields
7               EC2A                                    Shoreditch
8               EC2M                   Broadgate, Liverpool Street
9               EC2N                    Old Broad Street, Tower 42
10              EC2P                                           NaN
11              EC2R                               Bank of England
12              EC2V                                     Guildhall
13              EC2Y                                      Barbican
14              EC3A                          St Mary Axe, Aldgate
15              EC3M           Lloyd's of London, Fenchurch Street
16              EC3N                   Tower Hill, Tower of London
17              EC3P                                           NaN
18              EC3R                        Monument, Billingsgate
19              EC3V  Cornhill, Gracechurch Street, Lombard Street
20              EC4A                                   Fetter Lane
21              EC4M                                     St Paul's
22              EC4N                                 Mansion House
23              EC4P                                           NaN
24              EC4R                                 Cannon Street
25              EC4V                                   Blackfriars
26              EC4Y                                        Temple
27              EC50                                           NaN

In [10]:
df.dropna().reset_index(drop=True)

   Postcode district                                      Coverage
0               EC1A                     St Bartholomew's Hospital
1               EC1M                       Clerkenwell, Farringdon
2               EC1N                                 Hatton Garden
3               EC1R              Finsbury, Finsbury Estate (west)
4               EC1V      Finsbury (east), Moorfields Eye Hospital
5               EC1Y                     St Luke's, Bunhill Fields
6               EC2A                                    Shoreditch
7               EC2M                   Broadgate, Liverpool Street
8               EC2N                    Old Broad Street, Tower 42
9               EC2R                               Bank of England
10              EC2V                                     Guildhall
11              EC2Y                                      Barbican
12              EC3A                          St Mary Axe, Aldgate
13              EC3M           Lloyd's of London, Fenchurch Street
14              EC3N                   Tower Hill, Tower of London
15              EC3R                        Monument, Billingsgate
16              EC3V  Cornhill, Gracechurch Street, Lombard Street
17              EC4A                                   Fetter Lane
18              EC4M                                     St Paul's
19              EC4N                                 Mansion House
20              EC4R                                 Cannon Street
21              EC4V                                   Blackfriars
22              EC4Y                                        Temple

# Finding Latitudes and Longitudes

In [33]:
df2=pd.read_csv("https://www.doogal.co.uk/UKPostcodesCSV.ashx?area=London")
df2.head()

,Postcode,In Use?,Latitude,Longitude,Easting,Northing,Grid Ref,County,District,Ward,...,User Type,Last updated,Nearest station,Distance to station,Postcode area,Postcode district,Police force,Water company,Plus Code,Average Income
0,BR1 1AA,Yes,51.401546,0.015415,540291,168873,TQ402688,Greater London,Bromley,Bromley Town,...,0,2020-02-19,Bromley South,0.218257,BR,BR1,Metropolitan Police,Thames Water,9F32C228+J5,63100
1,BR1 1AB,Yes,51.406333,0.015208,540262,169405,TQ402694,Greater London,Bromley,Bromley Town,...,0,2020-02-19,Bromley North,0.253666,BR,BR1,Metropolitan Police,Thames Water,9F32C248+G3,56100
2,BR1 1AD,No,51.400057,0.016715,540386,168710,TQ403687,Greater London,Bromley,Bromley Town,...,1,2020-02-19,Bromley South,0.044559,BR,BR1,Metropolitan Police,NaN,9F32C228+2M,63100
3,BR1 1AE,Yes,51.404543,0.014195,540197,169204,TQ401692,Greater London,Bromley,Bromley Town,...,0,2020-02-19,Bromley North,0.462939,BR,BR1,Metropolitan Police,Thames Water,9F32C237+RM,63100
4,BR1 1AF,Yes,51.401392,0.014948,540259,168855,TQ402688,Greater London,Bromley,Bromley Town,...,0,2020-02-19,Bromley South,0.227664,BR,BR1,Metropolitan Police,Thames Water,9F32C227+HX,63100

In [34]:
df2.drop(columns=["In Use?","Easting","Northing","Grid Ref","County","District","Ward","User Type","Last updated","Nearest station","Distance to station","Postcode area","Police force","Water company","Plus Code","Average Income"],axis=1,inplace=True)

In [35]:
df2.head()

,Postcode,Latitude,Longitude,District Code,Ward Code,Country,County Code,Constituency,Introduced,Terminated,...,LSOA Code,Local authority,MSOA Code,Middle layer super output area,Parish Code,Census output area,Constituency Code,Index of Multiple Deprivation,Quality,Postcode district
0,BR1 1AA,51.401546,0.015415,E09000006,E05000109,England,E11000009,Bromley and Chislehurst,2016-05-01,NaN,...,E01000675,NaN,E02000144,Bromley 018,E43000196,E00003264,E14000604,24305,1,BR1
1,BR1 1AB,51.406333,0.015208,E09000006,E05000109,England,E11000009,Bromley and Chislehurst,2012-03-01,NaN,...,E01000676,NaN,E02000134,Bromley 008,E43000196,E00003255,E14000604,13716,1,BR1
2,BR1 1AD,51.400057,0.016715,E09000006,E05000109,England,E11000009,Bromley and Chislehurst,2014-09-01,2017-09-01,...,E01000675,NaN,E02000144,Bromley 018,E43000196,E00003264,E14000604,24305,1,BR1
3,BR1 1AE,51.404543,0.014195,E09000006,E05000109,England,E11000009,Bromley and Chislehurst,2008-08-01,NaN,...,E01000677,NaN,E02000144,Bromley 018,E43000196,E00003266,E14000604,20694,1,BR1
4,BR1 1AF,51.401392,0.014948,E09000006,E05000109,England,E11000009,Bromley and Chislehurst,2015-05-01,NaN,...,E01000675,NaN,E02000144,Bromley 018,E43000196,E00003264,E14000604,24305,1,BR1

In [30]:
df2.columns

Index(['Postcode', 'Latitude', 'Longitude', 'District Code', 'Ward Code',
       'Country', 'County Code', 'Constituency', 'Introduced', 'Terminated',
       'Parish', 'National Park', 'Population', 'Households', 'Built up area',
       'Built up sub-division', 'Lower layer super output area', 'Rural/urban',
       'Region', 'Altitude', 'London zone', 'LSOA Code', 'Local authority',
       'MSOA Code', 'Middle layer super output area', 'Parish Code',
       'Census output area', 'Constituency Code',
       'Index of Multiple Deprivation', 'Quality', 'Postcode district'],
      dtype='object')

In [39]:
df2.reset_index(drop=True)

        Postcode   Latitude  Longitude Postcode district
0        BR1 1AA  51.401546   0.015415               BR1
1        BR1 1AB  51.406333   0.015208               BR1
2        BR1 1AD  51.400057   0.016715               BR1
3        BR1 1AE  51.404543   0.014195               BR1
4        BR1 1AF  51.401392   0.014948               BR1
5        BR1 1AG  51.401392   0.014948               BR1
6        BR1 1AH  51.400441   0.017390               BR1
7        BR1 1AJ  51.400489   0.018833               BR1
8        BR1 1AL  51.406549   0.013130               BR1
9        BR1 1AX  51.408226   0.017578               BR1
10       BR1 1BA  51.399090   0.015436               BR1
11       BR1 1BB  51.398192   0.015397               BR1
12       BR1 1BP  51.409027   0.010236               BR1
13       BR1 1BQ  51.408058   0.015874               BR1
14       BR1 1BS  51.407276   0.010045               BR1
15       BR1 1BT  51.399140   0.012563               BR1
16       BR1 1BU  51.409074   0.010123               BR1
17       BR1 1BW  51.398997   0.016165               BR1
18       BR1 1BX  51.407276   0.010045               BR1
19       BR1 1BY  51.408116   0.010898               BR1
20       BR1 1BZ  51.408226   0.017578               BR1
21       BR1 1DA  51.407153   0.017229               BR1
22       BR1 1DB  51.407276   0.010045               BR1
23       BR1 1DD  51.403891   0.016582               BR1
24       BR1 1DE  51.408562   0.010590               BR1
25       BR1 1DF  51.408899   0.010360               BR1
26       BR1 1DG  51.409191   0.010068               BR1
27       BR1 1DH  51.409027   0.010236               BR1
28       BR1 1DJ  51.403890   0.016593               BR1
29       BR1 1DL  51.409192   0.010042               BR1
...          ...        ...        ...               ...
321804  WC2R 3NJ  51.512436  -0.113812              WC2R
321805  WC2R 3NL  51.512436  -0.113812              WC2R
321806  WC2R 3WE  51.512216  -0.113591              WC2R
321807  WC2R 3WY  51.516327  -0.123769              WC2R
321808  WC2R 3WZ  51.516327  -0.123769              WC2R
321809  WC2R 3XP  51.524565  -0.112042              WC2R
321810  WC99 0LF  51.516327  -0.123769              WC99
321811  WC99 9AP  51.511651  -0.125446              WC99
321812   WD2 1NT  51.631728  -0.334886               WD2
321813   WD2 1NX  51.632168  -0.334205               WD2
321814  WD23 1NT  51.631732  -0.334862              WD23
321815  WD23 1NX  51.632159  -0.334220              WD23
321816   WD3 1PZ  51.614605  -0.450354               WD3
321817   WD3 2UR  51.623684  -0.495017               WD3
321818   WD3 2UT  51.622684  -0.496278               WD3
321819   WD3 2UU  51.624958  -0.494816               WD3
321820   WD3 2UW  51.627896  -0.496741               WD3
321821   WD3 2UX  51.626503  -0.493999               WD3
321822   WD3 2UY  51.628894  -0.497431               WD3
321823   WD3 8UE  51.626396  -0.494089               WD3
321824   WD3 8UF  51.626209  -0.494225               WD3
321825   WD3 8UR  51.628270  -0.496469               WD3
321826   WD3 8UT  51.622684  -0.496278               WD3
321827   WD3 8UU  51.625014  -0.494750               WD3
321828   WD3 8UW  51.623983  -0.495253               WD3
321829   WD3 8UX  51.626871  -0.495107               WD3
321830   WD3 8UZ  51.626955  -0.494143               WD3
321831   WD3 8XD  51.628575  -0.499204               WD3
321832   WD6 2RN  51.643292  -0.255958               WD6
321833   WD6 2RW  51.642309  -0.256627               WD6

[321834 rows x 4 columns]

In [41]:
df3=df2.drop_duplicates(subset="Postcode district")

In [43]:
df3.drop(columns=["Postcode"],axis=1,inplace=True)
df3.reset_index(drop=True)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

      Latitude  Longitude Postcode district
0    51.401546   0.015415               BR1
1    51.407775  -0.003321               BR2
2    51.407682  -0.032385               BR3
3    51.380973  -0.011615               BR4
4    51.386370   0.064750               BR5
5    51.374644   0.093075               BR6
6    51.416161   0.067962               BR7
7    51.366941   0.054250               BR8
8    51.589310   0.266958              CM13
9    51.609021   0.260054              CM14
10   51.528566  -0.116476              CM23
11   51.340340  -0.005061               CR0
12   51.347927  -0.089572               CR2
13   51.310936  -0.085498               CR3
14   51.410383  -0.147321               CR4
15   51.382348  -0.132875              CR44
16   51.313816  -0.136376               CR5
17   51.320934  -0.059164               CR6
18   51.394161  -0.115780               CR7
19   51.338530  -0.110651               CR8
20   51.333332  -0.003872               CR9
21   51.375716  -0.091863              CR90
22   51.444759   0.182007               DA1
23   51.426481   0.105038              DA14
24   51.435850   0.101123              DA15
25   51.462949   0.114474              DA16
26   51.490770   0.147253              DA17
27   51.496327   0.149272              DA18
28   51.441780   0.149990               DA5
29   51.449761   0.138979               DA6
..         ...        ...               ...
299  51.522937  -0.143535               W1W
300  51.511678  -0.149238               W1X
301  51.510964  -0.142739               W1Y
302  51.516375  -0.175251                W2
303  51.519838  -0.268414                W3
304  51.501346  -0.254217                W4
305  51.528642  -0.297937                W5
306  51.495135  -0.227414                W6
307  51.518505  -0.337894                W7
308  51.504690  -0.193009                W8
309  51.522735  -0.181195                W9
310  51.516595  -0.129279              WC1A
311  51.518137  -0.128970              WC1B
312  51.522822  -0.133337              WC1E
313  51.522983  -0.129885              WC1H
314  51.524571  -0.125276              WC1N
315  51.518266  -0.120144              WC1R
316  51.518435  -0.113896              WC1V
317  51.523789  -0.111717              WC1X
318  51.517941  -0.113959              WC2A
319  51.514374  -0.119713              WC2B
320  51.513721  -0.122767              WC2E
321  51.513033  -0.129237              WC2H
322  51.511512  -0.127412              WC2N
323  51.510588  -0.120258              WC2R
324  51.516327  -0.123769              WC99
325  51.631728  -0.334886               WD2
326  51.631732  -0.334862              WD23
327  51.614605  -0.450354               WD3
328  51.643292  -0.255958               WD6

[329 rows x 3 columns]

In [45]:
df4=df.join(df3.set_index("Postcode district"),on="Postcode district")

In [49]:
df4.head()

  Postcode district                          Coverage   Latitude  Longitude
0              EC1A         St Bartholomew's Hospital  51.525136  -0.111183
1              EC1M           Clerkenwell, Farringdon  51.521357  -0.106597
2              EC1N                     Hatton Garden  51.518160  -0.109514
3              EC1P                               NaN  51.524567  -0.112017
4              EC1R  Finsbury, Finsbury Estate (west)  51.523208  -0.106379

In [52]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    branca-0.4.0               |             py_0          26 KB  conda-forge
    openssl-1.1.1g             |       h516909a_0         2.1 MB  conda-forge
    certifi-2020.4.5.1         |   py36h9f0ad1d_0         151 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

    altair:          4.1.0-py_1        conda-forge
    branca:          0.4.0-py_0        conda-forge
    folium:          0.5.0-py_0        conda-forge
    python_abi:      3.6-1_cp36m       conda-forge
    vincent:         0.4.4-py_1        conda-forge

The following packages will be UPDATED:

    ca-certificates: 2020.1.1-0                    --> 2020.4.5.1-hecc5488_0     conda-forge
    certifi:         2020.4.5.1-py36_0             --> 2020.4.5.1-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0             --> 1.1.1g-h516909a_0         conda-forge


Downloading and Extracting Packages
vincent-0.4.4        | 28 KB     | ##################################### | 100%
branca-0.4.0         | 26 KB     | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
certifi-2020.4.5.1   | 151 KB    | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
ca-certificates-2020 | 146 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Libraries imported.

In [53]:
address="City of London"

In [64]:
geolocator = Nominatim(user_agent="LO_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of the City of London are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of the City of London are 51.5073219, -0.1276474.

In [72]:
map_london = folium.Map(location=[latitude, longitude], zoom_start=14)

# add markers to map
for lat, lng, coverage in zip(df4['Latitude'], df4['Longitude'], df4['Coverage']):
    label = '{}'.format(coverage)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_london)  
    
map_london

In [73]:
CLIENT_ID = 'ZWIKCFD0SM53OQFRR0RI5QDJNT1CGUFOMSEK4DLML1XIYHAB' # your Foursquare ID
CLIENT_SECRET = 'BB0T2COSTCS5Y0B25CCNA2LE3AIRFIKVHQMOCNC2RE1LWYVJ' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version
LIMIT = 100 

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: ZWIKCFD0SM53OQFRR0RI5QDJNT1CGUFOMSEK4DLML1XIYHAB
CLIENT_SECRET:BB0T2COSTCS5Y0B25CCNA2LE3AIRFIKVHQMOCNC2RE1LWYVJ

In [76]:
def get_nearby_venues(names, postal_codes, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, postal_code, lat, lng in zip(names, postal_codes, latitudes, longitudes):
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            postal_code,
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = [
                  'Postcode district',
                  'Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [77]:
venues = get_nearby_venues(
    names=df4['Coverage'],
    postal_codes = df4['Postcode district'],
    latitudes=df4['Latitude'],
    longitudes=df4['Longitude']
)

In [78]:
venues.shape

(2079, 8)

In [79]:
venues.groupby("Postcode district").count()

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Postcode district,,,,,,,
EC1A,100,100,100,100,100,100,100
EC1M,57,57,57,57,57,57,57
EC1N,84,84,84,84,84,84,84
EC1P,0,63,63,63,63,63,63
EC1R,100,100,100,100,100,100,100
EC1V,71,71,71,71,71,71,71
EC1Y,98,98,98,98,98,98,98
EC2A,41,41,41,41,41,41,41
EC2M,77,77,77,77,77,77,77
EC2N,100,100,100,100,100,100,100
EC2P,0,61,61,61,61,61,61
EC2R,59,59,59,59,59,59,59
EC2V,100,100,100,100,100,100,100
EC2Y,100,100,100,100,100,100,100
EC3A,100,100,100,100,100,100,100
EC3M,41,41,41,41,41,41,41
EC3N,71,71,71,71,71,71,71
EC3P,0,61,61,61,61,61,61
EC3R,33,33,33,33,33,33,33
EC3V,80,80,80,80,80,80,80
EC4A,100,100,100,100,100,100,100
EC4M,100,100,100,100,100,100,100
EC4N,100,100,100,100,100,100,100
EC4P,0,61,61,61,61,61,61
EC4R,37,37,37,37,37,37,37
EC4V,38,38,38,38,38,38,38
EC4Y,85,85,85,85,85,85,85
EC50,0,61,61,61,61,61,61

In [80]:
venues_onehot = pd.get_dummies(venues[['Venue Category']], prefix="", prefix_sep="")
venues_onehot.insert(0, 'Postcode district', venues['Postcode district'])

In [81]:
venues_grouped = venues_onehot.groupby('Postcode district').mean().reset_index()

In [82]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [83]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Postcode district']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Postcode district'] = venues_grouped['Postcode district']

for ind in np.arange(venues_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(venues_grouped.iloc[ind, :], num_top_venues)

In [84]:
neighborhoods_venues_sorted.head()

,Postcode district,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,EC1A,Pub,Café,Coffee Shop,Vietnamese Restaurant,Pizza Place,Bar,Food Truck,Cocktail Bar,Italian Restaurant,French Restaurant
1,EC1M,Coffee Shop,Pub,Hotel,Food Truck,Vietnamese Restaurant,Bar,Wine Bar,Falafel Restaurant,Gym / Fitness Center,Modern European Restaurant
2,EC1N,Coffee Shop,Pub,Sandwich Place,Sushi Restaurant,Food Truck,French Restaurant,Gym / Fitness Center,Falafel Restaurant,Wine Bar,Vietnamese Restaurant
3,EC1P,Pub,Bar,Garden,Cocktail Bar,Coffee Shop,Hotel,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place
4,EC1R,Pub,Coffee Shop,Cocktail Bar,Vietnamese Restaurant,Hotel,Café,Bar,Italian Restaurant,Pizza Place,Food Truck

In [86]:
kclusters = 10

venues_grouped_clustering = venues_grouped.drop('Postcode district', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(venues_grouped_clustering)

In [87]:
kmeans.labels_[0:10]

array([1, 8, 3, 1, 1, 2, 2, 5, 0, 0], dtype=int32)

In [88]:
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

In [89]:
venues_merged = df4

In [90]:
venues_merged = venues_merged.join(neighborhoods_venues_sorted.set_index('Postcode district'), on='Postcode district')

In [91]:
is_NaN = venues_merged.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = venues_merged[row_has_NaN]
rows_with_NaN

,Postcode district,Coverage,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
3,EC1P,NaN,51.524567,-0.112017,1,Pub,Bar,Garden,Cocktail Bar,Coffee Shop,Hotel,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place
10,EC2P,NaN,51.524503,-0.112088,1,Pub,Bar,Garden,Coffee Shop,Hotel,Cocktail Bar,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place
17,EC3P,NaN,51.524503,-0.112088,1,Pub,Bar,Garden,Coffee Shop,Hotel,Cocktail Bar,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place
23,EC4P,NaN,51.524503,-0.112088,1,Pub,Bar,Garden,Coffee Shop,Hotel,Cocktail Bar,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place
27,EC50,NaN,51.524503,-0.112088,1,Pub,Bar,Garden,Coffee Shop,Hotel,Cocktail Bar,Middle Eastern Restaurant,Food Truck,Pizza Place,Sandwich Place

In [92]:
venues_merged.dropna(inplace=True)

In [93]:
venues_merged = venues_merged.astype({"Cluster Labels": int})

In [96]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=14)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(venues_merged['Latitude'], venues_merged['Longitude'], venues_merged['Coverage'], venues_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

# Finding the Best possible location

In [97]:
venues_merged.loc[venues_merged['Cluster Labels'] == 0, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
8,"Broadgate, Liverpool Street",Cocktail Bar,Hotel,Restaurant,Pub,Gym / Fitness Center,Italian Restaurant,Salad Place,Breakfast Spot,Boxing Gym,Coffee Shop
9,"Old Broad Street, Tower 42",Coffee Shop,Cocktail Bar,Hotel,Gym / Fitness Center,Restaurant,French Restaurant,Salad Place,Italian Restaurant,Steakhouse,Café
14,"St Mary Axe, Aldgate",Hotel,Gym / Fitness Center,Cocktail Bar,Coffee Shop,French Restaurant,Indian Restaurant,Italian Restaurant,Garden,Wine Bar,Restaurant
16,"Tower Hill, Tower of London",Hotel,Coffee Shop,Cocktail Bar,Salad Place,Wine Bar,French Restaurant,Gym / Fitness Center,Restaurant,Pizza Place,Middle Eastern Restaurant
19,"Cornhill, Gracechurch Street, Lombard Street",Coffee Shop,Gym / Fitness Center,Hotel,Restaurant,Sandwich Place,Cocktail Bar,Café,Steakhouse,Salad Place,French Restaurant

In [98]:
venues_merged.loc[venues_merged['Cluster Labels'] == 1, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,St Bartholomew's Hospital,Pub,Café,Coffee Shop,Vietnamese Restaurant,Pizza Place,Bar,Food Truck,Cocktail Bar,Italian Restaurant,French Restaurant
4,"Finsbury, Finsbury Estate (west)",Pub,Coffee Shop,Cocktail Bar,Vietnamese Restaurant,Hotel,Café,Bar,Italian Restaurant,Pizza Place,Food Truck

In [99]:
venues_merged.loc[venues_merged['Cluster Labels'] == 2, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
5,"Finsbury (east), Moorfields Eye Hospital",Coffee Shop,Food Truck,Pub,Hotel,Italian Restaurant,Vietnamese Restaurant,Gym / Fitness Center,Park,Fish & Chips Shop,Sushi Restaurant
6,"St Luke's, Bunhill Fields",Coffee Shop,Food Truck,Gym / Fitness Center,Italian Restaurant,Sandwich Place,Café,Concert Hall,Gastropub,Hotel,Indie Movie Theater

In [100]:
venues_merged.loc[venues_merged['Cluster Labels'] == 3, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
2,Hatton Garden,Coffee Shop,Pub,Sandwich Place,Sushi Restaurant,Food Truck,French Restaurant,Gym / Fitness Center,Falafel Restaurant,Wine Bar,Vietnamese Restaurant
20,Fetter Lane,Pub,Coffee Shop,Sandwich Place,Italian Restaurant,Wine Bar,Sushi Restaurant,Hotel,French Restaurant,Gym / Fitness Center,Café
21,St Paul's,Coffee Shop,Italian Restaurant,Pub,Wine Bar,Sandwich Place,Japanese Restaurant,Gym / Fitness Center,Falafel Restaurant,Modern European Restaurant,Plaza
26,Temple,Pub,Sandwich Place,Italian Restaurant,Coffee Shop,Wine Bar,Cocktail Bar,Sushi Restaurant,Hotel,Café,Building

In [101]:
venues_merged.loc[venues_merged['Cluster Labels'] == 4, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
11,Bank of England,Coffee Shop,Hotel,Restaurant,Steakhouse,Cocktail Bar,Boutique,Café,Boxing Gym,Event Space,Clothing Store
12,Guildhall,Coffee Shop,Gym / Fitness Center,Steakhouse,Restaurant,Italian Restaurant,Hotel,French Restaurant,Scenic Lookout,Clothing Store,Wine Bar
13,Barbican,Coffee Shop,Gym / Fitness Center,Sushi Restaurant,Clothing Store,Modern European Restaurant,Burger Joint,Cocktail Bar,Scenic Lookout,Café,Art Gallery
22,Mansion House,Coffee Shop,Gym / Fitness Center,Wine Bar,Italian Restaurant,French Restaurant,Restaurant,Seafood Restaurant,Hotel,Clothing Store,Steakhouse
24,Cannon Street,Gym / Fitness Center,Steakhouse,Vietnamese Restaurant,French Restaurant,Italian Restaurant,Seafood Restaurant,Coffee Shop,Cocktail Bar,Dim Sum Restaurant,Scenic Lookout

In [102]:
venues_merged.loc[venues_merged['Cluster Labels'] == 5, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
7,Shoreditch,Food Truck,Gym / Fitness Center,Coffee Shop,Boxing Gym,Indie Movie Theater,Poke Place,Pilates Studio,Café,Chinese Restaurant,Roof Deck

In [103]:
venues_merged.loc[venues_merged['Cluster Labels'] == 6, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
25,Blackfriars,Coffee Shop,Italian Restaurant,Vietnamese Restaurant,Seafood Restaurant,Salad Place,Roof Deck,Modern European Restaurant,Wine Bar,Cocktail Bar,Restaurant

In [104]:
venues_merged.loc[venues_merged['Cluster Labels'] == 7, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
15,"Lloyd's of London, Fenchurch Street",Hotel,Gym / Fitness Center,Italian Restaurant,French Restaurant,Garden,Sandwich Place,Pub,Event Space,Poke Place,South American Restaurant

In [105]:
venues_merged.loc[venues_merged['Cluster Labels'] == 8, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,"Clerkenwell, Farringdon",Coffee Shop,Pub,Hotel,Food Truck,Vietnamese Restaurant,Bar,Wine Bar,Falafel Restaurant,Gym / Fitness Center,Modern European Restaurant

In [106]:
venues_merged.loc[venues_merged['Cluster Labels'] == 9, venues_merged.columns[[1] + list(range(5, venues_merged.shape[1]))]]

,Coverage,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
18,"Monument, Billingsgate",Hotel,Coffee Shop,Gym / Fitness Center,History Museum,Scenic Lookout,French Restaurant,Garden,Japanese Restaurant,Souvenir Shop,South American Restaurant